version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27018:27017'

  socialmediadashboard:
    build: .
    image: socialapp
    ports:
      - '3003:3003'
    depends_on:
      - mongodb
    environment:
      PORT: 3003
      SECRET_KEY: 'your_secret_key'
